# Generated by Django 5.1.3 on 2024-12-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_editora_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="editora",
            name="cidade",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
