# Generated by Django 5.1.3 on 2025-02-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_compra_tipo_pagamento_alter_itenscompra_livro_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
